apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-env.example.yaml
  - ingress.example.yaml
  - secret.example.yaml
  - networkpolicy.example.yaml
