apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: genomeai-default-boundaries
  namespace: genomeai
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: genomeai
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: genomeai
