'use client';
import { useEffect, useMemo, useState } from 'react';
import { MetricCard, Card } from '@/components/ui/card';
import { FilterBar } from '@/components/ui/filter-bar';
import { ExplainabilityBlock } from '@/components/ui/explainability-block';
import { apiFetch } from '@/lib/api/client';
import type { AlertItem, ListResponse } from '@/lib/api/contracts';
import { normalizeListResponse } from '@/lib/api/contracts';
import { AlertList } from '@/components/operations/alert-list';

export function AlertsSurface(){const [data,setData]=useState<ListResponse<AlertItem>|null>(null);const [query,setQuery]=useState('');const [error,setError]=useState<string|null>(null);useEffect(()=>{void apiFetch<ListResponse<AlertItem>>('/alerts').then(res=>setData(normalizeListResponse(res))).catch(err=>setError(err instanceof Error?err.message:'Failed to load alerts'))},[]); const items=useMemo(()=>{const rows=data?.items||[]; if(!query)return rows; return rows.filter(item=>JSON.stringify(item).toLowerCase().includes(query.toLowerCase()))},[data,query]); const open=items.filter(item=>item.status!=='resolved').length; const critical=items.filter(item=>['critical','high'].includes(String(item.severity||'').toLowerCase())&&item.status!=='resolved').length; const multiSite=new Set(items.map(item=>item.entity?.farm_id||'unknown')).size>1; return <div className="grid"><div className="topbar"><div><h1 className="page-title">Alerts</h1><p className="page-subtitle">Daily triage surface with linked actions, explainability entry points and multi-site visibility.</p></div></div><FilterBar placeholder="Filter alerts by farm, entity, type or status…" onChange={setQuery} /><div className="grid grid-3"><MetricCard title="Visible alerts" value={items.length} /><MetricCard title="Open" value={open} /><MetricCard title="Critical / high" value={critical} /></div><ExplainabilityBlock reasons={['Alert generation stays in backend; React renders only canonical DTOs.','Decision and feedback hooks remain available from each alert card.','Farm references preserve single-farm and multi-site daily triage.']} />{multiSite?<Card><h3 className="card-title">Multi-site visibility</h3><p className="card-subtitle">Current alert slice spans multiple farms/sites. Daily parity evidence must preserve this scope in React.</p></Card>:null}{error?<div className="card error-text">{error}</div>:null}{!data?<div className="card">Loading alerts…</div>:null}{data?<AlertList items={items} />:null}</div>}
