'use client';
import { useEffect, useMemo, useState } from 'react';
import { MetricCard, Card } from '@/components/ui/card';
import { FilterBar } from '@/components/ui/filter-bar';
import { ExplainabilityBlock } from '@/components/ui/explainability-block';
import { apiFetch } from '@/lib/api/client';
import type { AlertItem, ListResponse } from '@/lib/api/contracts';
import { normalizeListResponse } from '@/lib/api/contracts';
import { AlertList } from '@/components/operations/alert-list';

export function AlertsSurface(){const [data,setData]=useState<ListResponse<AlertItem>|null>(null);const [query,setQuery]=useState('');const [error,setError]=useState<string|null>(null);useEffect(()=>{void apiFetch<ListResponse<AlertItem>>('/alerts').then(res=>setData(normalizeListResponse(res))).catch(err=>setError(err instanceof Error?err.message:'Ошибка загрузки алертов'))},[]); const items=useMemo(()=>{const rows=data?.items||[]; if(!query)return rows; return rows.filter(item=>JSON.stringify(item).toLowerCase().includes(query.toLowerCase()))},[data,query]); const open=items.filter(item=>item.status!=='resolved').length; const critical=items.filter(item=>['critical','high'].includes(String(item.severity||'').toLowerCase())&&item.status!=='resolved').length; const multiSite=new Set(items.map(item=>item.entity?.farm_id||'unknown')).size>1; return <div className="grid"><div className="topbar"><div><h1 className="page-title">Инсайты</h1><p className="page-subtitle">Ежедневный мониторинг алертов с привязкой к решениям и объяснениям.</p></div></div><FilterBar placeholder="Фильтр по ферме, объекту, типу или статусу…" onChange={setQuery} /><div className="grid grid-3"><MetricCard title="Всего алертов" value={items.length} /><MetricCard title="Открытых" value={open} /><MetricCard title="Критических / высоких" value={critical} /></div><ExplainabilityBlock reasons={['Алерты генерируются бэкендом; React отображает только канонические DTO.','Действия и обратная связь доступны из каждой карточки алерта.','Ссылки на фермы обеспечивают работу в одно- и мультисайтовом режимах.']} />{multiSite?<Card><h3 className="card-title">Мультисайтовый просмотр</h3><p className="card-subtitle">Текущий срез алертов охватывает несколько ферм/сайтов.</p></Card>:null}{error?<div className="card error-text">{error}</div>:null}{!data?<div className="card">Загружаю алерты…</div>:null}{data?<AlertList items={items} />:null}</div>}
