'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Card, MetricCard } from '@/components/ui/card';
import { ExplainabilityBlock } from '@/components/ui/explainability-block';
import { WorklistList } from '@/components/ui/worklist-list';
import { apiFetch } from '@/lib/api/client';
import type { PlannerResponse } from '@/lib/api/contracts';
import { DailyBriefPreview } from '@/components/operations/daily-brief-preview';
import { buildDailyBriefPreview } from '@/components/operations/daily-brief-preview';
import type { DailyOperationsBundle } from '@/lib/api/daily-operations';

export function PlannerSurface(){const [data,setData]=useState<PlannerResponse|null>(null);const [error,setError]=useState<string|null>(null);useEffect(()=>{void apiFetch<PlannerResponse>('/planner').then(setData).catch(err=>setError(err instanceof Error?err.message:'Ошибка загрузки планировщика'))},[]); return <div className="grid"><div className="topbar"><div><h1 className="page-title">Операционный планировщик</h1><p className="page-subtitle">Недельные планы, просроченные задачи и предварительная сводка дня.</p></div></div><ExplainabilityBlock reasons={['Сводки планировщика и счётчики подтверждений поступают из бэкенд API.','React не перестраивает логику планирования; только компонует DTO для удобства оператора.']} />{error?<div className="card error-text">{error}</div>:null}{!data?<div className="card">Загружаю планировщик…</div>:<><div className="grid grid-3"><MetricCard title="Открытых задач" value={data.summary.tasks_open} /><MetricCard title="Просроченных" value={data.summary.overdue_active} /><MetricCard title="Ожидают подтверждения" value={data.pending_approvals} /></div><DailyBriefPreview brief={buildDailyBriefPreview({me:{schema:'stub',user:{user_id:0,username:'stub',role:'viewer',permissions:[]},session:{session_id:'stub',client_kind:'web',auth_transport:'bearer',status:'active',created_at:'',updated_at:''},scope:{tenant_id:'default',allowed_farm_ids:[],allowed_site_ids:[]}},alerts:{schema:'stub',total:0,items:[]},worklists:{schema:'stub',total:data.overdue_items.length,items:data.overdue_items},planner:data,reports:{schema:'stub',total:0,items:[]},decisionIntelligence:{schema:'stub',summary:{total_decisions:0,accepted_feedback:0,rejected_feedback:0,acceptance_rate:0,linked_alerts:0},top_actions:[],latest_decisions:[]},feedback:{schema:'stub',total:0,items:[],metrics:{acceptance_rate:0}}} as unknown as DailyOperationsBundle)} /><Card><h3 className="card-title">Недельные планы</h3><div className="table-wrap"><table className="table"><thead><tr><th>Название</th><th>Статус</th><th>Начало недели</th><th>Задач</th><th>Ферма</th></tr></thead><tbody>{data.weekly_plans.map(plan=><tr key={plan.plan_id}><td>{plan.name}</td><td>{plan.status}</td><td>{plan.week_start}</td><td>{plan.item_count}</td><td>{plan.farm_id||'—'}</td></tr>)}</tbody></table></div></Card><WorklistList items={data.overdue_items} /><Card><h3 className="card-title">Связанные ссылки</h3><div className="linked-inline-actions"><Link href="/worklists">Дневные рабочие списки</Link><Link href="/reports">Отчёты для сводки дня</Link><Link href="/assistant?target=planner">Объяснить планировщик</Link></div></Card></>}</div>}
